export enum Events {
    READY = 'ready',
    RESUMED = 'resume',
    RECONNECT = 'recoonect',
    INVALID_SESSION = 'InvalidSession',
    CHANNEL_CREATE = 'ChannelCreate',
    CHANNEL_UPDATE = 'ChannelUpdate', 
    CHANNEL_DELETED = 'ChannelDeleted',
    CHANNEL_PINS_UPDATED = 'ChannelPinsUpdated',
    GUILD_Create = 'GuildCreate',
    GUILD_UPDATE = 'GuildUpdate',
    GUILD_DELETE = 'GuildDelete',
    GUILD_BAN_ADD = 'GuildBanAdd',
    GUILD_BAN_REMOVE = 'GuildBanRemove',
    GUILD_EMOJIS_UPDATE = 'GuildEmojisUpdate',
    GUILD_MEMBER_ADD = 'GuildMemberAdd',
    GUILD_MEMBER_UPDATE = 'GuildMemberUpdate',
    GUILD_MEMBER_REMOVE = 'GuildMemberRemove',
    GUILD_MEMBERS_CHUNK = 'GuildMembersChunk',
    DEBUG = 'debug',
    ERROR = 'error',
    MESSAGE_CREATE = 'message,'
}